repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
  - name: metallb
    url: https://metallb.github.io/metallb


environments:
  default:
    values:
    - values.yaml

releases:
{{ if .Values.tls.enabled }}
##### CERT MANAGER #####
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  set:
  - name: installCRDs
    value: true

##### ISTIO #####
- name: istio
  namespace: istio-system
  wait: true
  chart: istio/base

- name: istiod
  namespace: istio-system
  chart: istio/istiod
  wait: true
  needs:
  - istio-system/istio

- name: istio-ingressgateway
  namespace: istio-ingress
  chart: istio/gateway
  wait: true
  set: 
  - name: service.loadBalancerIP
    value: {{ .Values.istio.gateways.ingressgateway.loadBalancerIP }}
  needs:
  - istio-system/istio

- name: istio-config
  namespace: istio-system
  chart: istio-config
  disableValidationOnInstall: true
  needs:
  - istio-system/istio
{{ end }}
##### METALLB #####
- name: metallb
  namespace: metallb-system
  chart: metallb/metallb
  wait: true

- name: metallb-config
  namespace: metallb-system
  chart: metallb-config
  disableValidationOnInstall: true
  needs:
  - metallb-system/metallb

##### AUTH HANDLER #####
- name: auth-handler
  namespace: auth-handler
  chart: auth-handler
  disableValidationOnInstall: true
  set:
  - name: tls.enabled
    value: {{ .Values.tls.enabled }}
  - name: gateway.host
    value: "auth.{{ .Values.istio.gateways.ingressgateway.loadBalancerIP }}.nip.io"
{{ if .Values.tls.enabled }}
  hooks:
  - events:
      - presync
    showlogs: true
    command: sh
    args:
      - -c
      - "kubectl create namespace auth-handler || exit 0"
  - events:
      - presync
    showlogs: true
    command: sh
    args:
      - -c
      - "kubectl label namespace auth-handler istio-injection=enabled || exit 0"
  needs:
    - istio-system/istiod
    - istio-ingress/istio-ingressgateway
    - istio-system/istio-config
    - metallb-system/metallb-config
{{ end }}