repositories:
 - name: jetstack
   url: https://charts.jetstack.io
 - name: istio
   url: https://istio-release.storage.googleapis.com/charts


environments:
  default:
    values:
    - values.yaml

releases:
{{ if .Values.tls.enabled }}
- name: cert-manager
  namespace: cert-manager
  createNamespace: true   
  chart: jetstack/cert-manager
  set:
  - name: installCRDs
    value: true
- name: istio
  namespace: istio-system
  createNamespace: true   
  chart: istio
  disableValidationOnInstall: true
  needs:
  - cert-manager/cert-manager
- name: istiod
  namespace: istio-system
  createNamespace: true   
  chart: istio/istiod
  disableValidationOnInstall: true
  needs:
  - istio-system/istio
{{ end }}
- name: auth-handler
  namespace: auth-handler
  chart: auth-handler
  disableValidationOnInstall: true
  set:
  - name: tls.enabled
    value: {{ .Values.tls.enabled }}
{{ if .Values.tls.enabled }}
  hooks:
  - events:
      - presync
    showlogs: true
    command: sh
    args:
      - -c
      - "kubectl create namespace auth-handler || exit 0"
  - events:
      - presync
    showlogs: true
    command: sh
    args:
      - -c
      - "kubectl label namespace auth-handler istio-injection=enabled || exit 0"
  needs:
    - istio-system/istiod
{{ end }}