apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-handler.name" . }}-gateway-proxy-service
spec:
  selector:
    app: {{ include "auth-handler.name" . }}-gateway-proxy
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 443
