apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "auth-handler.name" . }}-virtual-service
spec:
  hosts:
  - {{ .Values.gateway.host }}
  gateways:
  - {{ include "auth-handler.name" . }}-gateway
  tls:
  - match:
    - port: 443
      sniHosts:
      - "{{ .Values.gateway.host }}"
    route:
    - destination:
        host: {{ include "auth-handler.name" . }}-gateway-proxy-service
        port:
          number: 443
