apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: {{ include "auth-handler.name" . }}-keycloak-realm-import
spec:
  keycloakCRName: {{ include "auth-handler.name" . }}-keycloak
  realm:
    realm: auth-handler
    displayName: "Authentication Handler"
    displayNameHtml: "Authentication Handler"
    rememberMe: true
    registrationAllowed: true
    enabled: true
    clients:
    - adminUrl: ${authBaseUrl}
      authorizationServicesEnabled: true
      baseUrl: /realms/auth-handler/authentication-handler/
      clientAuthenticatorType: client-secret
      clientId: authentication-handler
      defaultClientScopes:
      - web-origins
      - acr
      - profile
      - roles
      - email
      directAccessGrantsEnabled: true
      enabled: true
      name: Authentication handler
      optionalClientScopes:
      - address
      - phone
      - offline_access
      - microprofile-jwt
      protocol: openid-connect
      publicClient: false
      redirectUris:
      - "*"
      rootUrl: ${authBaseUrl}
      secret: {{ .Values.keycloak.client.secret }}