apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "auth-handler.name" . }}-virtual-service
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "auth-handler.name" . }}-gateway
  http:
  - match:
    - uri:
        exact: /realms/auth-handler/protocol/openid-connect/auth
    - uri:
        prefix: /resources
    route:
    - destination:
        host: "{{ include "auth-handler.name" . }}-keycloak-service"
        port:
          number: 8080