apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "auth-handler.name" . }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  {{ if .Values.tls.enabled }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - {{ .Values.gateway.host }}
  {{ else }}
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.gateway.host }}
  {{ end }}