apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "auth-handler.name" . }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - {{ .Values.gateway.host }}
