apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "auth-handler.name" . }}-keycloak-ingress
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "auth-handler.name" . }}-keycloak-service
                port:
                  number: 8080