{{ if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "auth-handler.name" . }}-keycloak-server-cert
spec:
  secretName: {{ include "auth-handler.name" . }}-keycloak-server-cert
  dnsNames: 
    - {{ .Values.ingress.host }}
  isCA: false
  usages:
    - server auth
  issuerRef:
    name: {{ include "auth-handler.name" . }}-keycloak-ca
{{ end }}