apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ include "auth-handler.name" . }}-keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: {{ include "auth-handler.name" . }}-keycloak-postgres-db
    usernameSecret:
      name: {{ include "auth-handler.name" . }}-keycloak-postgres-db-secret
      key: username
    passwordSecret:
      name: {{ include "auth-handler.name" . }}-keycloak-postgres-db-secret
      key: password
  http:
    httpEnabled: true
  hostname:
    strict: false
    strictBackchannel: false