apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "auth-handler.name" . }}-keycloak-postgresql-db
spec:
  serviceName: {{ include "auth-handler.name" . }}-keycloak-postgresql-db-service
  selector:
    matchLabels:
      app: {{ include "auth-handler.name" . }}-keycloak-postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "auth-handler.name" . }}-keycloak-postgresql-db
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: {{ include "auth-handler.name" . }}-keycloak-postgresql-db
          image: postgres:latest
          args:
          {{ if .Values.tls.enabled }}
            - "-c" 
            - "ssl=on"
            - "-c" 
            - "ssl_cert_file=/var/run/secrets/{{ include "auth-handler.name" . }}-postgres-server-cert/tls.crt"
            - "-c" 
            - "ssl_key_file=/var/run/secrets/{{ include "auth-handler.name" . }}-postgres-server-cert/tls.key"
            - "-c" 
            - "ssl_ca_file=/var/run/secrets/{{ include "auth-handler.name" . }}-postgres-server-cert/ca.crt"
            - "-c"
            - "hba_file=/etc/postgresql/pg_hba.conf"
          {{ end }}
          env:
          {{ if .Values.tls.enabled }}
            - name: PGSSLMODE
              value: verify-ca
          {{ end }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-handler.name" . }}-keycloak-postgres-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-handler.name" . }}-keycloak-postgres-db-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-handler.name" . }}-keycloak-postgres-db-secret
                  key: db
          volumeMounts:
          {{ if .Values.tls.enabled }}
          - name: {{ include "auth-handler.name" . }}-postgres-server-cert
            readOnly: true
            mountPath: "/var/run/secrets/{{ include "auth-handler.name" . }}-postgres-server-cert"
          - name: {{ include "auth-handler.name" . }}-postgres-hba-config
            readOnly: true
            mountPath: "/etc/postgresql"
          {{ end }}
      volumes:
        {{ if .Values.tls.enabled }}
        - name: {{ include "auth-handler.name" . }}-postgres-server-cert    
          secret:
            defaultMode: 416
            secretName: {{ include "auth-handler.name" . }}-postgres-server-cert
        - name: {{ include "auth-handler.name" . }}-postgres-hba-config    
          configMap:
            defaultMode: 416
            name: {{ include "auth-handler.name" . }}-postgres-hba-config
        {{ end }}
        
