{{ if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "auth-handler.name" . }}-postgres-ca-cert
  annotations:
spec:
  isCA: true
  commonName: {{ include "auth-handler.name" . }}-postgres
  secretName: {{ include "auth-handler.name" . }}-postgres-ca-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ include "auth-handler.name" . }}-issuer
    kind: Issuer
    group: cert-manager.io
{{ end }}