apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ include "auth-handler.name" . }}-keycloak-postgres-db-secret
data:
  db: {{ b64enc .Values.postgres.auth.db }}
  username: {{ b64enc .Values.postgres.auth.username }}
  password: {{ b64enc .Values.postgres.auth.password }}