{{ if .Values.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "auth-handler.name" . }}-postgres-client-cert
spec:
  secretName: {{ include "auth-handler.name" . }}-postgres-client-cert
  dnsNames: 
    - keycloak.auth-handler.com
  isCA: false
  usages:
    - client auth
  issuerRef:
    name: {{ include "auth-handler.name" . }}-postgres-ca
{{ end }}