apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "auth-handler.name" . }}-postgres-server-cert
spec:
  secretName: {{ include "auth-handler.name" . }}-postgres-server-cert
  isCA: false
  usages:
    - server auth
  dnsNames: 
    - {{ include "auth-handler.name" . }}-keycloak-postgres-db
  issuerRef:
    name: {{ include "auth-handler.name" . }}-postgres-ca
