apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-handler.name" . }}-keycloak-postgres-db
spec:
  selector:
    app: {{ include "auth-handler.name" . }}-keycloak-postgresql-db
  type: ClusterIP
  ports:
  - port: {{ .Values.postgres.service.port }}
    targetPort: 5432