apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "auth-handler.name" . }}-postgres-client-cert
spec:
  secretName: {{ include "auth-handler.name" . }}-postgres-client-cert
  commonName: {{ .Values.postgres.auth.username }}
  isCA: false
  usages:
    - client auth
  issuerRef:
    name: {{ include "auth-handler.name" . }}-postgres-ca
